- name: create ec2-user and route53
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-010df9efe26d8371c
    sg_id: sg-02c4c043a85fe8c60
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
    zone: hinatadream.online
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instance
  
  - name: print outputs
    ansible.builtin.debug:
      msg: "{{ec2_instance}}"
  
     