- name: devops course information
  host: web
  became: yes
  vars:
   course: "devops with aws"
   duration: 120
   topics:
   - linux
   - shell scripting
   - ansible
   - terraform
   - aws
   - k8
   lives: true
   tools:
    cl: jenkins
    cm: ansible 
    cloud: aws
  
  tasks:
  - name: course information
    ansible.builtin.debug:
     msg: "i am learing {{course}},with  duration {{duration}}, topics {{topics}} and lives: {{lives}}, tools {{tools}}"
     
