- name: demo on fillters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
      msg: "hello {{ course | default ('ansible') }}"
  
  - name: convert to uppercase
    vars:
     greeting: "hello ramesh"
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"
