- name: demo on fillters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
      msg: "hello {{ course | default ('ansible') }}"
  
  - name: convert to uppercase
    vars:
     greeting: "hello ramesh"
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"
  
  - name: convert to lowercase
    vars:
      greeting: "hello rakesh"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"
  

  - name: get the unique value
    vars:
      numbers: [1,2,3,4,5,34,45,3,2,1]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"
  