- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print name
    ansible.builtin.debug:
      msg: hello {{item}}
    loop:
    - ramesh
    - rajesh
    - rahul
    - suresh
    