- name: print to variables
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
  - name: DURATION
    prompt: please enter the duration
  - name: please enter the trainer name

  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "I am learing {{COURSE}}, duration is: {{DURATION}} trainer is: {{TRAINER}}"
  