- name: variables to print
  hosts: web
  vars:
   COURSE: "Devops with aws"
   DURATION: "120 HRS"
   TRAINER: "siva kumar"
  tasks:
  - name: print the nformation
    ansible.builtin.debug:
      msg: "I am learing {{COURSE}}, duration is: {{DURATION}} trainer is: {{TRAINER}}"
  