- name: print to variables
  hosts: web
  vars:
  - vars.yaml
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "I am learing {{COURSE}}, duration is: {{DURATION}} trainer is: {{TRAINER}}"